services:
  db:
    build: ./database
    container_name: db-tesis
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME:-Docker-Tesis}
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-huachimingo}
    ports:
      - "${DB_HOST_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_NAME:-Docker-Tesis}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend-tesis
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=${PORT:-3000}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-huachimingo}
      - DATABASE=${DB_NAME:-Docker-Tesis}
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_KEY=${COOKIE_KEY}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend_net
      - frontend_net

  frontend:
    build: ./frontend
    container_name: frontend-tesis
    restart: always
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    depends_on:
      - backend
    networks:
      - frontend_net

networks:
  frontend_net:
  backend_net:

volumes:
  postgres_data: